# -*- mode: Makefile -*-

# Check Python 2 and Python 3 give identical results
# (might as well parallelise for multicore)
test:
	make -f Makefile.test -j 2 check-2 check-3
	diff -ur 2 3
check-2:
	mkdir -p 2
	cd 2 && python2.7 ../css-generate.py > list
check-3:
	mkdir -p 3
	cd 3 && python3 ../css-generate.py > list
